# Generated by Django 4.2.5 on 2023-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Revision', 'Revision'), ('Resubmition', 'Resubmition'), ('Pending', 'Pending')], default='New', max_length=20),
        ),
    ]
