# Generated by Django 4.2.5 on 2023-10-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('writer_assigned', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Revision', 'Revision'), ('Resubmission', 'Resubmission'), ('Pending', 'Pending')], default='New', max_length=20)),
                ('attachment', models.FileField(upload_to='projects')),
            ],
        ),
    ]
