# Generated by Django 4.2.5 on 2023-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, default='avator.png', null=True, upload_to='images'),
        ),
    ]
