# Generated by Django 4.2.5 on 2023-10-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='book_balance',
            field=models.CharField(max_length=255),
        ),
    ]
